# Generated by Django 5.0 on 2023-12-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
