# Generated by Django 5.0 on 2024-01-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_alter_hiretuber_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiretuber',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='hiretuber',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
