# Generated by Django 5.0 on 2023-12-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
