# Generated by Django 5.0 on 2023-12-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0005_rename_full_name_contact_fulllname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fulllname',
            new_name='fullname',
        ),
    ]
