# Generated by Django 5.0 on 2024-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0006_rename_fulllname_contact_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
