# Generated by Django 5.0 on 2024-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0009_rename_fullname_contact_fn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fn',
            new_name='full_name',
        ),
    ]
