# Generated by Django 5.0 on 2024-01-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0010_rename_fn_contact_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='fname',
        ),
    ]
