# Generated by Django 5.0 on 2023-12-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
