# Generated by Django 5.0 on 2024-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_camera_type_alter_youtuber_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='media/ytubers/%Y/%m/'),
            preserve_default=False,
        ),
    ]
