# Generated by Django 5.0 on 2024-01-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_youtuber_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtuber',
            name='thumbnail',
        ),
    ]
